version: "3.8"

services:
  vr_zed_container:
    image: juanr55/zed_rostcp:v2
    container_name: vr_zed_container
    runtime: nvidia
    privileged: true
    network_mode: "host"
    ipc: "host"
    pid: "host"
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /dev/shm:/dev/shm
      - /usr/local/zed/resources:/usr/local/zed/resources
      - /usr/local/zed/settings:/usr/local/zed/settings
      - /home/juan55/NakamaRL/docker_containers/zed:/simple_ws
    stdin_open: true
    tty: true
    command: ["/bin/bash"]

