services:
  vr_zed_container:
    image: juanr55/zed_rostcp:v5
    container_name: vr_zed_container
    runtime: nvidia
    privileged: true
    network_mode: "host"
    ipc: "host"
    pid: "host"
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=55
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /dev/shm:/dev/shm
      - /usr/local/zed/resources:/usr/local/zed/resources
      - /usr/local/zed/settings:/usr/local/zed/settings
      - ~/VR_Interface/simple_ws:/simple_ws
    stdin_open: true
    tty: true
    command: ["/bin/bash","-c", "source /opt/ros/humble/setup.bash && cd ~/simple_ws && source install/setup.bash && ros2 launch middle_nodes zed_vr_conexion.launch.py"]

