services:
  franka_ros2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    image: franka_container:latest #Change the name accordingly if you pulled the image or build it
    container_name: interface_fr3
    network_mode: "host"
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./:/home/user/simple_ws/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./limits.conf:/etc/security/limits.conf
      - /dev:/dev
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      ROS_DOMAIN_ID: 55
    group_add:
      - "dialout"
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    command: |
      bash -c "source /opt/ros/humble/setup.bash && \
               source /home/user/ros2_ws/install/setup.bash && \
               ros2 launch franka_teleop_pkg teleop.launch.py && \
               exec bash"
