services:
  vr_zed_container:
    image: zed_container:latest # Change the image name accordingly if you build it or pulled it
    container_name: vr_zed_container
    runtime: nvidia
    privileged: true
    network_mode: "host"
    ipc: "host"
    pid: "host"
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=55
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - /dev/shm:/dev/shm
      - ./:/simple_ws2
    stdin_open: true
    tty: true
    command: |
      bash -c "source /opt/ros/humble/setup.bash && \
               source /root/ros2_ws/install/setup.bash && \
               exec bash"
# ros2 launch middle_nodes zed_vr_conexion.launch.py 
